from viper.lexer import (
    NEWLINE, INDENT, PERIOD, COMMA, COLON, OPEN_PAREN as OP, CLOSE_PAREN as CP, ARROW,
    Number as Num,
    Name as N,
    Class as C,
    Operator as Op,
)


lexemes = [
    N('interface'), C('Shape'), COLON, NEWLINE,
    INDENT, N('def'), N('get_area'), OP, CP, ARROW, C('Float'), NEWLINE,
    NEWLINE,
    C('Shape'), C('Circle'), COLON, NEWLINE,
    INDENT, N('def'), N('init'), OP, N('radius'), COLON, C('Int'), CP, COLON, NEWLINE,
    INDENT, INDENT, N('self'), PERIOD, N('radius'), COLON, C('Int'), Op('='), N('radius'), NEWLINE,
    NEWLINE,
    INDENT, N('def'), N('get_area'), OP, CP, ARROW, C('Float'), COLON, NEWLINE,
    INDENT, INDENT, N('return'), N('pi'), Op('*'), OP, N('self'), PERIOD, N('radius'), Op('^'), Num('2'), CP,
    NEWLINE,
    NEWLINE,
    C('Shape'), C('Quadrilateral'), COLON, NEWLINE,
    INDENT, N('def'), N('init'), OP, N('length'), COLON, C('Int'), COMMA, N('width'), COLON, C('Int'), CP,
    COLON, NEWLINE,
    INDENT, INDENT, N('self'), PERIOD, N('length'), COLON, C('Int'), Op('='), N('length'), NEWLINE,
    INDENT, INDENT, N('self'), PERIOD, N('width'), COLON, C('Int'), Op('='), N('width'), NEWLINE,
    NEWLINE,
    INDENT, N('def'), N('get_area'), OP, CP, ARROW, C('Float'), COLON, NEWLINE,
    INDENT, INDENT, N('return'), N('self'), PERIOD, N('length'), Op('*'), N('self'), PERIOD, N('width'), NEWLINE,
    NEWLINE,
    C('Quadrilateral'), C('Rectangle'), COLON, NEWLINE,
    INDENT, N('pass'), NEWLINE,
    NEWLINE,
    C('Quadrilateral'), C('Square'), COLON, NEWLINE,
    INDENT, N('def'), N('init'), OP, N('side'), COLON, C('Int'), CP, COLON, NEWLINE,
    INDENT, INDENT, N('self'), PERIOD, N('length'), COLON, C('Int'), Op('='), N('side'), NEWLINE,
    INDENT, INDENT, N('self'), PERIOD, N('width'), COLON, C('Int'), Op('='), N('side'), NEWLINE,
]
